'use client';

import { Cpu, ChevronRight, Shield, AlertTriangle, Target, User, Zap, Lock } from 'lucide-react';

interface Props {
  analysis: string;
}

// Map section title keywords → icon + accent color
function getSectionMeta(title: string): { icon: React.ComponentType<{ size?: number; color?: string }>; color: string } {
  const t = title.toLowerCase();
  if (/risk|level|severity/i.test(t))   return { icon: AlertTriangle, color: '#ff4444' };
  if (/recommend|action|defense/i.test(t)) return { icon: Shield, color: '#00ff88' };
  if (/impact|damage|consequence/i.test(t)) return { icon: Zap, color: '#a855f7' };
  if (/actor|profile|motivation/i.test(t)) return { icon: User, color: '#f97316' };
  if (/chain|progression|step/i.test(t)) return { icon: Target, color: '#ff8c00' };
  if (/threat|attack|type/i.test(t))    return { icon: AlertTriangle, color: '#ff6b6b' };
  return { icon: Lock, color: '#00d4ff' };
}

function renderInline(text: string) {
  return text
    .replace(/\*\*(.*?)\*\*/g, '<strong style="color:#ffd700;font-weight:700;">$1</strong>')
    .replace(/`(.*?)`/g, '<code style="font-family:\'JetBrains Mono\',monospace;background:rgba(0,0,0,0.4);padding:1px 6px;border-radius:4px;color:#00ff88;font-size:11px;letter-spacing:0.3px;">$1</code>')
    .replace(/\*(.*?)\*/g, '<em style="color:#94a3b8;">$1</em>');
}

function RiskBadge({ text }: { text: string }) {
  const upper = text.toUpperCase();
  const isCrit  = upper.includes('CRITICAL');
  const isHigh  = upper.includes('HIGH');
  const isMed   = upper.includes('MEDIUM');
  const isLow   = upper.includes('LOW');

  const color = isCrit ? '#ff2222' : isHigh ? '#ff8c00' : isMed ? '#ffd700' : isLow ? '#00ff88' : '#00d4ff';
  const bg    = isCrit ? 'rgba(255,34,34,0.12)' : isHigh ? 'rgba(255,140,0,0.12)' : isMed ? 'rgba(255,215,0,0.1)' : isLow ? 'rgba(0,255,136,0.1)' : 'rgba(0,212,255,0.1)';
  const label = isCrit ? '🔴 CRITICAL' : isHigh ? '🟠 HIGH' : isMed ? '🟡 MEDIUM' : isLow ? '🟢 LOW' : text.trim();

  if (!isCrit && !isHigh && !isMed && !isLow) return null;

  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center', gap: 6,
      padding: '4px 14px', borderRadius: 20, fontSize: 12, fontWeight: 800,
      letterSpacing: 1, background: bg,
      border: `1px solid ${color}60`, color,
    }}>
      {label}
    </span>
  );
}

export default function AIAnalysisCard({ analysis }: Props) {
  // Split into sections on '## ' headers
  const rawSections = analysis.split(/\n(?=##\s)/);

  return (
    <div>
      {/* Header */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        marginBottom: 20, paddingBottom: 16, borderBottom: '1px solid var(--border)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{
            width: 36, height: 36, borderRadius: 10, display: 'flex',
            alignItems: 'center', justifyContent: 'center',
            background: 'linear-gradient(135deg, rgba(0,212,255,0.25), rgba(0,255,136,0.1))',
            border: '1px solid rgba(0,212,255,0.4)',
          }}>
            <Cpu size={18} color="var(--cyan)" />
          </div>
          <div>
            <div style={{ fontSize: 13, fontWeight: 800, color: 'var(--cyan)', letterSpacing: 0.5 }}>
              ASI-1 THREAT INTELLIGENCE REPORT
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 1 }}>
              Generated by ASI-1 AI · {new Date().toLocaleString()}
            </div>
          </div>
        </div>
        <div style={{
          display: 'flex', alignItems: 'center', gap: 6,
          padding: '4px 12px', borderRadius: 20,
          background: 'rgba(0,255,136,0.08)', border: '1px solid rgba(0,255,136,0.25)',
        }}>
          <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#00ff88', boxShadow: '0 0 6px #00ff88', animation: 'pulse-glow 2s ease-in-out infinite' }} />
          <span style={{ fontSize: 10, color: '#00ff88', fontWeight: 700, letterSpacing: 1 }}>AI ANALYZED</span>
        </div>
      </div>

      {/* Sections */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {rawSections.map((section, i) => {
          const lines = section.trim().split('\n');
          const rawTitle = lines[0]?.replace(/^##\s*/, '').trim() || '';
          const bodyLines = lines.slice(1).map(l => l.trim()).filter(Boolean);

          // No header → it's intro prose
          if (!rawTitle) {
            const text = bodyLines.join(' ');
            if (!text) return null;
            return (
              <div key={i} style={{
                fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.8,
                padding: '14px 16px', borderRadius: 10,
                background: 'rgba(255,255,255,0.015)', border: '1px solid var(--border)',
              }}
                dangerouslySetInnerHTML={{ __html: renderInline(text) }}
              />
            );
          }

          const { icon: Icon, color } = getSectionMeta(rawTitle);
          const isRecom = /recommend|action|defense/i.test(rawTitle);
          const isRisk  = /risk|level|severity/i.test(rawTitle);

          const bullets = bodyLines.filter(l => /^[-•*\d]/.test(l));
          const prose   = bodyLines.filter(l => !/^[-•*\d]/.test(l) && !/^#{1,3}\s/.test(l));

          return (
            <div key={i} style={{
              borderRadius: 12, overflow: 'hidden',
              border: `1px solid ${color}25`,
              animation: `fadeSlideIn 0.35s ease ${i * 0.06}s both`,
            }}>
              {/* Title row */}
              <div style={{
                display: 'flex', alignItems: 'center', gap: 10,
                padding: '10px 16px',
                background: `linear-gradient(90deg, ${color}14, ${color}05)`,
                borderBottom: `1px solid ${color}20`,
              }}>
                <Icon size={14} color={color} />
                <span style={{ fontSize: 11, fontWeight: 800, color, textTransform: 'uppercase', letterSpacing: 1.2, flex: 1 }}>
                  {rawTitle}
                </span>
                {isRisk && <RiskBadge text={bodyLines.join(' ')} />}
              </div>

              {/* Body */}
              <div style={{ padding: '14px 16px', background: 'rgba(0,0,0,0.1)' }}>
                {/* Prose paragraphs */}
                {prose.length > 0 && (
                  <div style={{ marginBottom: bullets.length ? 12 : 0 }}>
                    {prose.map((line, j) => {
                      // Sub-headings inside sections
                      if (/^#{2,3}\s/.test(line) || /^\*\*.*\*\*:?\s*$/.test(line)) {
                        return (
                          <div key={j} style={{ fontSize: 11, fontWeight: 700, color, textTransform: 'uppercase', letterSpacing: 0.8, marginTop: j ? 10 : 0, marginBottom: 4 }}
                            dangerouslySetInnerHTML={{ __html: renderInline(line.replace(/^#{2,3}\s*/, '').replace(/\*\*/g, '')) }} />
                        );
                      }
                      return (
                        <p key={j} style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.75, margin: '4px 0' }}
                          dangerouslySetInnerHTML={{ __html: renderInline(line) }} />
                      );
                    })}
                  </div>
                )}

                {/* Bullet list */}
                {bullets.length > 0 && (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                    {bullets.map((line, j) => {
                      const clean = line.replace(/^[-•*]\s*|\d+\.\s*/, '').trim();
                      return isRecom ? (
                        /* Recommended actions → action-button style */
                        <div key={j} style={{
                          display: 'flex', alignItems: 'flex-start', gap: 10,
                          padding: '9px 14px', borderRadius: 8,
                          background: 'rgba(0,255,136,0.04)',
                          border: '1px solid rgba(0,255,136,0.14)',
                          transition: 'background 0.2s',
                        }}>
                          <ChevronRight size={13} color="#00ff88" style={{ flexShrink: 0, marginTop: 2 }} />
                          <span style={{ fontSize: 12, color: 'var(--text-primary)', lineHeight: 1.65 }}
                            dangerouslySetInnerHTML={{ __html: renderInline(clean) }} />
                        </div>
                      ) : (
                        /* Generic bullets */
                        <div key={j} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, padding: '3px 0' }}>
                          <span style={{ color, fontSize: 9, flexShrink: 0, marginTop: 5 }}>▶</span>
                          <span style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.7 }}
                            dangerouslySetInnerHTML={{ __html: renderInline(clean) }} />
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <style>{`
        @keyframes fadeSlideIn {
          from { opacity: 0; transform: translateY(8px); }
          to   { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </div>
  );
}
